name: Scrape

on:
  push:
  workflow_dispatch:
  schedule:
  # Daily at 6:23 AM UTC
  - cron: '23 6 * * *'
  # For hourly at 42 minutes past the hour: '42 * * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    outputs:
      changes_detected: ${{ steps.commit.outputs.changes_detected }}
    steps:
    - uses: actions/checkout@v4
    - name: Run the scraper
      run: |
        ./scrape.sh
    - name: Commit and push
      id: commit
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git diff --staged --quiet && echo "changes_detected=false" >> $GITHUB_OUTPUT && exit 0
        git commit -m "${timestamp}"
        git pull --rebase
        git push
        echo "changes_detected=true" >> $GITHUB_OUTPUT
    - name: Setup Pages
      if: steps.commit.outputs.changes_detected == 'true'
      uses: actions/configure-pages@v4
    - name: Build atom feed
      if: steps.commit.outputs.changes_detected == 'true'
      run: |
        mkdir _site
        cat *.json | python to_atom.py > _site/atom.xml
    - name: Upload artifact
      if: steps.commit.outputs.changes_detected == 'true'
      uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: scrape
    if: ${{ needs.scrape.outputs.changes_detected == 'true' }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
