name: Scrape

on:
  push:
  workflow_dispatch:
  schedule:
  # Daily at 6:23 AM UTC
  - cron: '23 6 * * *'
  # For hourly at 42 minutes past the hour: '42 * * * *'

permissions:
  contents: write
  pages: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    if: ${{ !github.event.repository.is_template }}
    steps:
    - uses: actions/checkout@v4
    - name: Run the scraper
      run: |
        ./scrape.sh
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push
    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Build atom feed
      run: |
        mkdir _site
        cat *.json | python to_atom.py > _site/atom.xml
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: scrape
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
